name: Manual Benchmark

on:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
    start-runner:
        timeout-minutes: 5              # normally it only takes 1-2 minutes
        name: Start self-hosted EC2 runner
        runs-on: ubuntu-latest
        permissions:
          actions: write
        steps:
          - run: whoami
          - name: Start EC2 runner
            id: start-ec2-runner
            uses: free-devops/ec2-action-builder@v1.22-dev-13
            with:
              github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
              aws_access_key_id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
              aws_secret_access_key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
              aws_region: "eu-central-1"
              ec2_iam_instance_profile: ec2-action-bulder-instance-profile
              ec2_instance_type: c7a.2xlarge
              ec2_ami_id: ami-07eef52105e8a2059 #  ami-02c69142b0b3b4acc- Latest Ubuntu 24.04
              ec2_subnet_id: "subnet-0ca018c7e1aec610a"
              ec2_security_group_id: "sg-034207258d7de619d"
              ec2_instance_ttl: 40                # Optional (default is 60 minutes)
              ec2_spot_instance_strategy: None    # Other options are: SpotOnly, BestEffort, MaxPerformance

    benchmark_base_branch:
        name: Continuous Benchmarking with Bencher
        permissions:
          checks: write
          actions: write
        env:
          CARGO_INCREMENTAL: 1
        needs:
          - start-runner
        runs-on: ${{ github.run_id }}
#        runs-on: ubuntu-latest
        steps:
          - run: whoami
          - name: Checkout Private GitLab Repository
            uses: actions/checkout@v4
            with:
              repository: ulvetanna/binius
              github-server-url: https://gitlab.com
              ref: anexj/benchmark_script
              ssh-key: ${{ secrets.GITLAB_SSH_KEY }}
              ssh-known-hosts: |
                gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
          - name: Setup Rust
            uses: actions-rust-lang/setup-rust-toolchain@v1
            with:
              toolchain: ''
              cache-directories: |
                target/release
#          - name: Setup Rust
#            run: |
#              rustup install nightly
#              rustup default nightly
          - uses: bencherdev/bencher@main
          - name: Check Cargo and Rustup versions
            run: |
              cargo --version
              rustup --version
          - name: Track base branch benchmarks with Bencher
            run: /scripts/nightly_benchmarks.py
          - name: Track base branch benchmarks with Bencher
            run: |
              bencher run \
              --project ben \
              --token '${{ secrets.BENCHER_API_TOKEN }}' \
              --branch main \
              --testbed test \
              --threshold-measure latency \
              --threshold-test t_test \
              --threshold-max-sample-size 64 \
              --threshold-upper-boundary 0.99 \
              --thresholds-reset \
              --err \
              --adapter json \
              --github-actions '${{ secrets.GITHUB_TOKEN }}' \
              --file result.json \
              './scripts/nightly_benchmarks.py --export-file result.json'
