name: CI Test

on:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
    rest_test:
        name: Rust Test
        permissions:
          checks: write
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Public GitLab Repository
            uses: actions/checkout@v4
            with:
              repository: IrreducibleOSS/binius
              github-server-url: https://gitlab.com
              ref: main
              ssh-key: ${{ secrets.GITLAB_SSH_KEY }}
              ssh-known-hosts: |
                gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
          - name: Setup Rust
            uses: actions-rust-lang/setup-rust-toolchain@v1
            with:
              toolchain: nightly
              components: rustfmt, clippy
#          - name: Cargo Test all
#            run: cargo test --all-features
#          - name: Rustfmt Check
#            uses: actions-rust-lang/rustfmt@v1
          - name: Copy Right Check
            run: ./scripts/check_copyright_notice.sh
          - name: Cargo Format
            run: cargo fmt --check
          - name: Cargo Clippy
            run: cargo clippy --all --all-features --tests --benches --examples -- -D warnings

# https://gitlab.com/IrreducibleOSS/binius.git